version: '3.7'

services:
  backend-app-swarm:
    image: quench/hello:latest
    ports:
      - "8085:80"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    # environment:
    #   REDIS_URL: redis:6379
    # depends_on:
    #  - redis
    # networks:
    #   - webnet

# networks:
#   webnet:
#     driver: overlay
#     attachable: true
